// Copyright (c) 2017 The Bitcoin developers

#ifndef CONFIG_H
#define CONFIG_H


#define HAVE_ENDIAN_H 1
/* #undef HAVE_SYS_ENDIAN_H */

#define HAVE_DECL_HTOLE16 1
#define HAVE_DECL_HTOBE16 1
#define HAVE_DECL_BE16TOH 1
#define HAVE_DECL_LE16TOH 1
#define HAVE_DECL_HTOBE32 1
#define HAVE_DECL_HTOLE32 1
#define HAVE_DECL_BE32TOH 1
#define HAVE_DECL_LE32TOH 1
#define HAVE_DECL_HTOBE64 1
#define HAVE_DECL_HTOLE64 1
#define HAVE_DECL_BE64TOH 1
#define HAVE_DECL_LE64TOH 1

#define HAVE_BYTESWAP_H 1

#define HAVE_DECL_BSWAP_16 1
#define HAVE_DECL_BSWAP_32 1
#define HAVE_DECL_BSWAP_64 1

#define HAVE_SYS_SELECT_H 1
#define HAVE_SYS_PRCTL_H 1

#define HAVE_DECL___BUILTIN_CLZ 1
#define HAVE_DECL___BUILTIN_CLZL 1
#define HAVE_DECL___BUILTIN_CLZLL 1

#define HAVE_MALLOPT_ARENA_MAX 1
#define HAVE_MALLOC_INFO 1

#define HAVE_THREAD_LOCAL 1

#define HAVE_DECL_STRNLEN 1
#define HAVE_DECL_DAEMON 1

#endif // CONFIG_H
